<div>
  {!! $settings->getDocumentSettings()['contract_footer'] !!}

  <style>
    .footer .page-number:after { content: counter(page); }
  </style>

  <div class="footer fixed-section">
    <div class="left">
      <span class="report-time">08/05/2016 09:43:06</span><br>
      <span class="promo">Generated by QuickEMR.com</span>
    </div>

    <div class="center">
      <span class="signature-warning">Document Electronically Signed</span>
    </div>

    <div class="right">
      <span class="page-number">Page </span>
    </div>
  </div>

  <div class="text-sm text-gray mt-1">
    Page { PAGE_NUM } of { PAGE_COUNT } | Issued on {{ $date }} by {{ $generatedBy }}
  </div>
</div>
